spring:
  application:
    name: biblioteca-gateway-service
  security:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: biblioteca-auth-auth
          uri: lb://BIBLIOTECA-AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
        - id: biblioteca-auth-user
          uri: lb://BIBLIOTECA-AUTHENTICATION-SERVICE
          predicates:
            - Path=/user/**
        - id: biblioteca-service
          uri: lb://BIBLIOTECA-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8006/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
    preferIpAddress: true
 
jwt:
  secret: SjFkWjI5ajFic2RzNTZjMnl6ZHNkNHU4MjFlNGY3ZzZoc2Q3ZDhkM2l3cTB2NHV3Z3M5cmZjN2E0cTNyMzB1
 
server:
  port: 8007
